0.8 - Allow for Embedded or External MariaDB

diff --git a/install/etc/cont-init.d/10-freepbx b/install/etc/cont-init.d/10-freepbx
--- a/install/etc/cont-init.d/10-freepbx
+++ b/install/etc/cont-init.d/10-freepbx
@@ -1,55 +1,59 @@
 #!/usr/bin/with-contenv bash
 
-  ### Adjust NGINX Runtime Variables
- # UPLOAD_MAX_SIZE=${UPLOAD_MAX_SIZE:="2G"}
- # PHP_TIMEOUT=${PHP_TIMEOUT:-"600"}
- # sed -i -e "s/<UPLOAD_MAX_SIZE>/$UPLOAD_MAX_SIZE/g" /etc/nginx/nginx.conf
- # sed -i -e "s/<PHP_TIMEOUT>/$PHP_TIMEOUT/g" /etc/nginx/conf.d/default.conf
-  
 ### Set Debug Mode
 if [ "$DEBUG_MODE" = "TRUE" ] || [ "$DEBUG_MODE" = "true" ]; then
     set -x
 fi
 
-### Sanity Test
-if [ ! -n "DB_HOST" ]; then
-    echo '** [freepbx] ERROR: No Database Host Entered! '
-    exit 1
-fi
+ ## Embedded DB Variance
+  if [[ "$DB_EMBEDDED" = "FALSE" ]] && [[ "$DB_EMBEDDED" = "false" ]];  then
+:    
+  fi
 
-if [ ! -n "DB_NAME" ]; then
-    echo '** [freepbx] ERROR: No Database Pass Entered! '
-    exit 1
-fi
+# Embedded DB Variance
+if [[ "$DB_EMBEDDED" = "FALSE" ]] && [[ "$DB_EMBEDDED" = "false" ]];  then
 
-if [ ! -n "DB_USER" ]; then
-    echo '** [freepbx] ERROR: No Database User Entered! '
-    exit 1
-fi
+    ### Sanity Test
+    if [ ! -n "DB_HOST" ]; then
+        echo '** [freepbx] ERROR: No Database Host Entered! '
+        exit 1
+    fi
 
-if [ ! -n "DB_PASS" ]; then
-    echo '** [freepbx] ERROR: No Database Pass Entered! '
-    exit 1
+    if [ ! -n "DB_NAME" ]; then
+        echo '** [freepbx] ERROR: No Database Pass Entered! '
+        exit 1
+    fi
+
+    if [ ! -n "DB_USER" ]; then
+        echo '** [freepbx] ERROR: No Database User Entered! '
+        exit 1
+    fi
+
+    if [ ! -n "DB_PASS" ]; then
+        echo '** [freepbx] ERROR: No Database Pass Entered! '
+        exit 1
+    fi
 fi
 
 ### Set Defaults
-#DB_PORT=${DB_PORT:-3306}
+DB_PORT=${DB_PORT:-3306}
 RTP_START=${RTP_START:-18000}
 RTP_END=${RTP_END:-20000}
 
-
-### Make sure that DB is accessible
-while true; do
-	mysqlcmd='mysql -u'$DB_USER' -h'$DB_HOST' -p'$DB_PASS 
-	out="`$mysqlcmd -e "SELECT COUNT(*) FROM information_schema.FILES;" 2>&1`"
-	echo "$out" | grep -E "COUNT|Enter" 2>&1 > /dev/null
-	if [ $? -eq 0 ]; then
-    	echo "** [freepbx] DB Server is available !"
-    	break
-	fi
-	echo "** [freepbx] DB Server unavailable, sleeping a little bit ..."
-	sleep 2
-done
+if [[ "$DB_EMBEDDED" = "FALSE" ]] && [[ "$DB_EMBEDDED" = "false" ]];  then
+    ### Make sure that DB is accessible
+    while true; do
+    	mysqlcmd='mysql -u'$DB_USER' -h'$DB_HOST' -p'$DB_PASS 
+    	out="`$mysqlcmd -e "SELECT COUNT(*) FROM information_schema.FILES;" 2>&1`"
+    	echo "$out" | grep -E "COUNT|Enter" 2>&1 > /dev/null
+    	if [ $? -eq 0 ]; then
+        	echo "** [freepbx] DB Server is available !"
+        	break
+    	fi
+    	echo "** [freepbx] DB Server unavailable, sleeping a little bit ..."
+    	sleep 2
+    done
+fi
 
 if [ ! -f /data/.installed ]; then
   echo '** [freepbx] Creating Default Configuration Files'
@@ -66,6 +70,8 @@ chown -R asterisk:asterisk /data
 ### Check if FreePBX Installed
 if [ ! -f /var/www/html/admin/index.php ]; then
 	echo '** [freepbx] New Install Detected - Please wait while we fetch FreePBX...'
+
+if [[ "$DB_EMBEDDED" = "FALSE" ]] && [[ "$DB_EMBEDDED" = "false" ]];  then
   cat <<EOF > /etc/odbc.ini
 [asteriskcdrdb]
 Description = MySQL connection to 'asteriskcdrdb' database
@@ -77,6 +83,7 @@ database = $DB_NAME
 Port = $DB_PORT
 option = 3
 EOF
+fi
 
     sudo -u asterisk gpg --refresh-keys --keyserver pgp.mit.edu >/dev/null 2>&1
     sudo -u asterisk gpg --keyserver pgp.mit.edu --recv-key 9F9169F4B33B4659 >/dev/null 2>&1
@@ -87,14 +94,20 @@ EOF
    	cd /usr/src/freepbx
    	cp -R /etc/odbc.ini /usr/src/freepbx/installlib/files/odbc.ini
    	./start_asterisk start 
-	sed -i -e "s/\$amp_conf\['AMPDBHOST'\] = 'localhost';/\$amp_conf\['AMPDBHOST'\] = '$DB_HOST';/g" /usr/src/freepbx/installlib/installcommand.class.php
+if [[ "$DB_EMBEDDED" = "FALSE" ]] && [[ "$DB_EMBEDDED" = "false" ]];  then
+  sed -i -e "s/\$amp_conf\['AMPDBHOST'\] = 'localhost';/\$amp_conf\['AMPDBHOST'\] = '$DB_HOST';/g" /usr/src/freepbx/installlib/installcommand.class.php
 	sed -i -e "s/\$amp_conf\['CDRDBNAME'\] : 'asteriskcdrdb',/\$amp_conf\['CDRDBNAME'\] : '$DB_NAME',/g" /usr/src/freepbx/installlib/installcommand.class.php
 	sed -i -e "s/\$amp_conf\['CDRDBNAME'\] : 'asteriskcdrdb',/\$amp_conf\['CDRDBNAME'\] : '$DB_NAME',/g" /usr/src/freepbx/amp_conf/htdocs/admin/bootstrap.php
-
+fi
 	echo '** [freepbx] Installing FreePBX'
+if [[ "$DB_EMBEDDED" = "FALSE" ]] && [[ "$DB_EMBEDDED" = "false" ]];  then
 	./install -n --dbuser=$DB_USER --dbpass=$DB_PASS --dbname=$DB_NAME --cdrdbname=$DB_NAME --webroot=/var/www/html
+else
+  ./install -n
+fi
 
-cat <<EOF > /etc/freepbx.conf
+if [[ "$DB_EMBEDDED" = "FALSE" ]] && [[ "$DB_EMBEDDED" = "false" ]];  then
+  cat <<EOF > /etc/freepbx.conf
 <?php
 \$amp_conf['AMPDBUSER'] = '$DB_USER';
 \$amp_conf['AMPDBPASS'] = '$DB_PASS';
@@ -110,11 +123,13 @@ cat <<EOF > /etc/freepbx.conf
 require_once('/var/www/html/admin/bootstrap.php');
 ?>
 EOF
-  
+fi
+
   echo '** [freepbx] Enabling Default Modules'
 	fwconsole ma upgrade framework core 
 	fwconsole ma download cdr
-	
+
+if [[ "$DB_EMBEDDED" = "FALSE" ]] && [[ "$DB_EMBEDDED" = "false" ]];  then	
   # CDR Hack
   mysql -u$DB_USER -p$DB_PASS -h$DB_HOST asterisk < /usr/src/freepbx/installlib/SQL/cdr.sql
   mysql -u$DB_USER -p$DB_PASS -h$DB_HOST -e 'USE '$DB_NAME'; UPDATE freepbx_settings SET `value` = "'$DB_HOST'" WHERE keyword = "CDRDBHOST"; UPDATE freepbx_settings SET `value` = "'$DB_NAME'" WHERE keyword = "CDRDBNAME"; UPDATE freepbx_settings SET `value` = "'$DB_PASS'" WHERE keyword = "CDRDBPASS"; UPDATE freepbx_settings SET `value` = "'$DB_USER'" WHERE keyword = "CDRDBUSER"; UPDATE freepbx_settings SET `value` = "mysql" WHERE keyword = "CDRDBTYPE"; UPDATE freepbx_settings SET `value` = "'$DB_PORT'" WHERE keyword = "CDRDBPORT"; UPDATE freepbx_settings SET `value` = "cdr" WHERE keyword = "CDRDBTABLENAME";'
@@ -123,7 +138,10 @@ EOF
 	sed -i -e 's/\$db_name = !empty(\$db_name) ? \$db_name : "asteriskcdrdb";/\$db_name = !empty(\$db_name) ? \$db_name : "'$DB_NAME'";/g' /www/freepbx/admin/modules/cdr/install.php
 	fwconsole ma install cdr
 	cp -R /var/www/html/admin/modules/cdr/.install.php /var/www/html/admin/modules/cdr/install.php
-	
+else
+  fwconsole ma install cdr
+fi
+
   fwconsole ma upgrade voicemail sipsettings infoservices featurecodeadmin logfiles callrecording dashboard music conferences 
   fwconsole ma upgrade certman userman pm2
 	fwconsole chown 
@@ -160,6 +178,21 @@ fi
 	  	touch /data/etc/amportal.conf
   fi
 
+  if [[ "$DB_EMBEDDED" = "TRUE" ]] && [[ "$DB_EMBEDDED" = "TRUE" ]];  then
+      if [ ! -f /data/etc/freepbx.conf ]; then
+         mkdir -p /data/etc/
+         cp -R /etc/freepbx.conf /data/etc/
+         rm -rf /etc/freepbx.conf
+         touch /data/etc/freepbx.conf
+         chown asterisk:asterisk /data/etc/freepbx.conf
+         ln -s /data/etc/freepbx.conf /etc/freepbx.conf
+      else
+         ln -s /data/etc/freepbx.conf /etc/freepbx.conf
+         touch /data/etc/freepbx.conf
+      fi
+  fi
+
+if [[ "$DB_EMBEDDED" = "FALSE" ]] && [[ "$DB_EMBEDDED" = "false" ]];  then
 ### Setup Dynamic Configuration
 echo '** [freepbx] Setting Configuration'
 cat <<EOF > /etc/freepbx.conf
@@ -190,6 +223,7 @@ database = $DB_NAME
 Port = $DB_PORT
 option = 3
 EOF
+fi
 
 if [ ! -f /etc/asterisk/cdr_adaptive_odbc.conf ]; then
 	cat <<EOF > /etc/asterisk/cdr_adaptive_odbc.conf
@@ -202,12 +236,14 @@ fi
 
 chown asterisk:asterisk /etc/freepbx.conf
 
+if [[ "$DB_EMBEDDED" = "FALSE" ]] && [[ "$DB_EMBEDDED" = "false" ]];  then
 ### Set RTP Ports
 echo '** [freepbx] Set RTP Ports' 
 mysql -u$DB_USER -p$DB_PASS -h$DB_HOST -e 'USE '$DB_NAME'; UPDATE sipsettings SET `data` = "'$RTP_START'" WHERE keyword = "rtpstart";  UPDATE sipsettings SET `data` = "'$RTP_FINISH'" WHERE keyword = "rtpend";'
 
 ### Fix a Freepbx bug with upgrades
 mysql -u$DB_USER -p$DB_PASS -h$DB_HOST -e 'USE '$DB_NAME'; ALTER TABLE featurecodes CHANGE column helptext helptext VARCHAR(10000);'
+fi
 
 echo '** [freepbx] Starting Asterisk'
 fwconsole chown > /dev/null 2>&1
